import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import "@/app/globals.css"
import { WishlistProvider } from "@/app/context/WishlistContext" // Adjust path if needed
import { CartProvider } from "@/app/context/CartContext" // Adjust path if needed


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'My Awesome App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WishlistProvider>
          {children}
        </WishlistProvider>
      </body>
    </html>
  );
}