// app/layout.tsx or app/RootLayout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/app/globals.css';
import { Toaster } from 'sonner'; // ✅ Toaster import
import { WishlistProvider } from '@/app/context/WishlistContext';
import { CartProvider } from '@/app/context/CartContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Comforty',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <WishlistProvider>
            <Toaster position="top-right" richColors /> {/* ✅ ADD THIS */}
            {children}
          </WishlistProvider>
        </CartProvider>
      </body>
    </html>
  );
}

